# 同步周期（秒），默认 1 天
interval_secs = 86400

# 所有下载产物的统一存储根目录
# 不支持运行时重载该配置，重启服务生效
storage_dir = "data"

# HTTP 下载服务器监听地址
# 不支持运行时重载该配置，重启服务生效
bind = "0.0.0.0:8080"

url = "localhost"

# grpc后台地址
admin = "0.0.0.0:25667"

# 可选代理（支持 http / socks5h）
proxy = "http://127.0.0.1:20171"
